# Base Configuration 
title: Kousher Alam
url: https://kousheralam.github.io
baseurl: ''


## Socila Links 
social_links:
  facebook: https://facebook.com/MdKousherAlam
  twitter: https://twitter.com/Kousheralam1
  linkedin: https://www.linkedin.com/in/kousheralam/
  github: https://github.com/kousherAlam
  stackoverflow: https://stackoverflow.com/cv/kousheralam
  npm: https://www.npmjs.com/~kousher


## Pagination 
pagination: 
  enabled: true
  per_page: 10


# Collection 
collections:
  demo:
    title: Demo
    output: true
  demo_category:
    title: Demo Category
    output: true
    permalink: /demo/:path
  portfolio:
    title: Portfolio
    output: true
  portfolio_category:
    title: Portfolio Category
    output: true
    permalink: /portfolio/:path
  post_category:
    title: Post Category
    output: true
    permalink: /portfolio/:path

## Default variables 
defaults:
  - scope:
      path: _portfolio
      type: portfolio
    values:
      layout: portfolio
      permalink: "/portfolio/:title:output_ext"
  - scope:
      path: _portfolio_category
      type: portfolio
    values:
      layout: portfolio-category
      permalink: "/portfolio/:title:output_ext"
  - scope:
      path: _demo
      type: demo
    values:
      layout: demo
      permalink: "/demo/:title:output_ext"
  - scope:
      path: _demo_category
      type: demo
    values:
      layout: demo-category
      permalink: "/demo/:title:output_ext"
  - scope:
      path: _posts
    values:
      layout: blog
      type: post
      permalink: "/blog/:categories/:year/:month/:day/:title:output_ext"
  - scope:
      path: _blog_category
      type: blog-category
    values:
      layout: blog-category
      permalink: "/blog/:categories/:title:output_ext"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-get-json
  - jekyll-paginate-v2
